MateAcademy-FE-study/wild-tigers.github.io

src/index.html
=> Anya`s index2

gulpfile.js, src/index.html, src/scss/_container.scss, src/scss/_general.scss, src/scss/_header.scss, src/scss/_variables.scss, src/scss/_welcome.scss, src/scss/main.scss
and fix to gulp to update page after any file changed
=> welcome markup

gulpfile.js, package.json, src/index.html, src/scss/_container.scss, src/scss/_header.scss, src/scss/_welcome.scss
=> V index html fix

gulpfile.js
=> fix for task

src/scss/_header.scss, src/scss/_welcome.scss, src/templates/partials/_header.html
=> welcome 52%

src/scss/_buttons.scss
=> delete margin-top from yellow button

src/scss/_buttons.scss
=> closes #61, add missing box shadow

src/scss/_buttons.scss
no changes.
just made _buttons.scss to look better
=> optimize style format

src/scss/_welcome.scss
=> arrow for welcome

src/scss/_features.scss, src/templates/partials/_features.html
=> added change svg on hover

src/scss/_services.scss, src/scss/main.scss, src/templates/partials/_services.html
=> K what we do section

src/scss/_process.scss, src/scss/_variables.scss, src/templates/partials/_process.html
added minimal style for section
=> draft for process section

src/scss/_normalize.scss, src/templates/partials/_history.html
=> recover _history.html & _normalize.scss

src/scss/_buttons.scss, src/scss/_container.scss, src/scss/_hire.scss, src/scss/_team.scss, src/templates/partials/_team.html
=> paddings and margins fixes

src/scss/_packages.scss, src/templates/partials/_packages.html
=> Packages done

src/scss/_header.scss, src/templates/layout.html, src/templates/partials/_header.html
=> burger menu

src/scss/_header.scss
=> navigation for horizontal screen orientation

src/scss/_buttons.scss, src/scss/_features.scss, src/scss/_history.scss, src/scss/_services.scss, src/scss/_variables.scss, src/scss/_welcome.scss
=> remove border on focus slider

src/scss/_header.scss, src/templates/partials/_header.html
=> add yellow border closes #93

src/templates/partials/_features.html, src/templates/partials/_footer.html, src/templates/partials/_hire_us.html, src/templates/partials/_history.html, src/templates/partials/_packages.html, src/templates/partials/_projects.html, src/templates/partials/_services.html, src/templates/partials/_support.html, src/templates/partials/_team.html, src/templates/partials/_welcome.html
=> change for all sections aos to fade-up

src/scss/_features.scss, src/scss/_header.scss, src/scss/_services.scss, src/templates/partials/_features.html, src/templates/partials/_services.html
=> S pp closes #114

src/js/script.js, src/scss/_hire.scss, src/scss/_modal.scss, src/templates/partials/_hire_us.html, src/templates/partials/_modal.html
=> modal for hire us

src/templates/layout.html, src/templates/partials/_welcome.html
=> remove aos for welcome and js fix
